# Systematic Similarity

## Data Preparation:
- The code starts by importing necessary libraries and loading a cleaned dataset (t2.csv).
- It defines functions to clean text data by removing punctuation and stopwords using NLTK.
- The dataset is then sliced to a smaller size (df1) due to computational limitations.

In [3]:
import numpy as np   #for numerical calculation
import pandas as pd  #for data analysis

import string 
import regex # regular expression
from nltk.corpus import stopwords # to remove stopwords using nltk library

In [4]:
df=pd.read_csv('t1.csv') # reading the data which we cleaned before

In [5]:
df.info() # data information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33573 entries, 0 to 33572
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   33573 non-null  int64  
 1   category     33573 non-null  object 
 2   description  33573 non-null  object 
 3   title        33573 non-null  object 
 4   brand        33573 non-null  object 
 5   date         33573 non-null  object 
 6   price        33573 non-null  float64
 7   asin         33573 non-null  object 
 8   imageURL     33573 non-null  object 
 9   overall      33573 non-null  int64  
 10  verified     33573 non-null  bool   
 11  reviewTime   33573 non-null  object 
 12  reviewText   33573 non-null  object 
 13  reviewerID   33573 non-null  object 
 14  Sentimental  33573 non-null  object 
dtypes: bool(1), float64(1), int64(2), object(11)
memory usage: 3.6+ MB


In [6]:
df.isnull().sum() # finding null values

Unnamed: 0     0
category       0
description    0
title          0
brand          0
date           0
price          0
asin           0
imageURL       0
overall        0
verified       0
reviewTime     0
reviewText     0
reviewerID     0
Sentimental    0
dtype: int64

In [7]:
df.head()

Unnamed: 0                                           category  \
0           0  ['Office Products', 'Office & School Supplies'...   
1           1  ['Office Products', 'Office & School Supplies'...   
2           2  ['Office Products', 'Office & School Supplies'...   
3           3  ['Office Products', 'Office & School Supplies'...   
4           4  ['Office Products', 'Office & School Supplies'...   

                                         description                  title  \
0  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
1  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
2  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
3  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
4  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   

                       brand        date  price        asin imageURL  overall  \
0  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        3   
1  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
2  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
3  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
4  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   

   verified   reviewTime                                         reviewText  \
0     False   11 3, 2006  I thought the book was entertaining and cute, ...   
1     False   05 9, 2006  This adorable story is an all time favorite fa...   
2     False  03 11, 2006  Lisa's bear Corduroy gets lost in the laundrom...   
3     False  01 24, 2001  In this installment of Corduroy's adventures w...   
4     False  07 30, 2000  Researchers constantly find that reading to ch...   

       reviewerID Sentimental  
0  A2WJLOXXIB7NF3     Neutral  
1  A1RKICUK0GG6VF    Positive  
2  A1QA5E50M398VW    Positive  
3  A3N0HBW8IP8CZQ    Positive  
4  A1K1JW1C5CUSUZ    Positive

In [8]:
df1=df[:10000] # slicing data because my pc doesnt support large data

## Text Cleaning:
- The product names, categories, and descriptions are cleaned using the defined text processing functions.
- Cleaned text is converted back to strings and combined into a single column (combined_text) for each product.

In [9]:
def text_process(text): # cleaning the data
    nopunc = [char for char in  text if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [10]:
def list_to_string(s): # converting list to string
    str1 = " "
    return (str1.join(s))

In [11]:
# cleaning the dataset
df1['Product_name']=df1['title'].apply(text_process)
df1['category_for_rec']=df1['category'].apply(text_process)
df1['description_for_rec']=df1['description'].apply(text_process)

C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\939280148.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Product_name']=df1['title'].apply(text_process)
C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\939280148.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['category_for_rec']=df1['category'].apply(text_process)
C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\939280148.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_i

In [12]:
# converting data from list to string
df1['Product_name']=df1['Product_name'].apply(list_to_string)
df1['category_for_rec']=df1['category_for_rec'].apply(list_to_string)
df1['description_for_rec']=df1['description_for_rec'].apply(list_to_string)

C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\1776642517.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Product_name']=df1['Product_name'].apply(list_to_string)
C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\1776642517.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['category_for_rec']=df1['category_for_rec'].apply(list_to_string)
C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\1776642517.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

In [13]:
df1.head()

Unnamed: 0                                           category  \
0           0  ['Office Products', 'Office & School Supplies'...   
1           1  ['Office Products', 'Office & School Supplies'...   
2           2  ['Office Products', 'Office & School Supplies'...   
3           3  ['Office Products', 'Office & School Supplies'...   
4           4  ['Office Products', 'Office & School Supplies'...   

                                         description                  title  \
0  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
1  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
2  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
3  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
4  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   

                       brand        date  price        asin imageURL  overall  \
0  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        3   
1  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
2  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
3  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
4  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   

   verified   reviewTime                                         reviewText  \
0     False   11 3, 2006  I thought the book was entertaining and cute, ...   
1     False   05 9, 2006  This adorable story is an all time favorite fa...   
2     False  03 11, 2006  Lisa's bear Corduroy gets lost in the laundrom...   
3     False  01 24, 2001  In this installment of Corduroy's adventures w...   
4     False  07 30, 2000  Researchers constantly find that reading to ch...   

       reviewerID Sentimental     Product_name  \
0  A2WJLOXXIB7NF3     Neutral  Pocket Corduroy   
1  A1RKICUK0GG6VF    Positive  Pocket Corduroy   
2  A1QA5E50M398VW    Positive  Pocket Corduroy   
3  A3N0HBW8IP8CZQ    Positive  Pocket Corduroy   
4  A1K1JW1C5CUSUZ    Positive  Pocket Corduroy   

                                    category_for_rec  \
0  Office Products Office School Supplies Educati...   
1  Office Products Office School Supplies Educati...   
2  Office Products Office School Supplies Educati...   
3  Office Products Office School Supplies Educati...   
4  Office Products Office School Supplies Educati...   

                                 description_for_rec  
0  Corduroy bear goes launderette Lisa overhears ...  
1  Corduroy bear goes launderette Lisa overhears ...  
2  Corduroy bear goes launderette Lisa overhears ...  
3  Corduroy bear goes launderette Lisa overhears ...  
4  Corduroy bear goes launderette Lisa overhears ...

In [14]:
df1['combined_text']=df1['Product_name']+' '+df1['category_for_rec']+' '+df1['description_for_rec'] #combining both column

C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\15092516.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['combined_text']=df1['Product_name']+' '+df1['category_for_rec']+' '+df1['description_for_rec'] #combining both column


In [15]:
df1.head()

Unnamed: 0                                           category  \
0           0  ['Office Products', 'Office & School Supplies'...   
1           1  ['Office Products', 'Office & School Supplies'...   
2           2  ['Office Products', 'Office & School Supplies'...   
3           3  ['Office Products', 'Office & School Supplies'...   
4           4  ['Office Products', 'Office & School Supplies'...   

                                         description                  title  \
0  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
1  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
2  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
3  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   
4  ['Corduroy the bear goes to the launderette wi...  A Pocket for Corduroy   

                       brand        date  price        asin imageURL  overall  \
0  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        3   
1  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
2  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
3  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   
4  Ingram Book & Distributor  2006-09-14   0.95  0140503528       []        5   

   verified   reviewTime                                         reviewText  \
0     False   11 3, 2006  I thought the book was entertaining and cute, ...   
1     False   05 9, 2006  This adorable story is an all time favorite fa...   
2     False  03 11, 2006  Lisa's bear Corduroy gets lost in the laundrom...   
3     False  01 24, 2001  In this installment of Corduroy's adventures w...   
4     False  07 30, 2000  Researchers constantly find that reading to ch...   

       reviewerID Sentimental     Product_name  \
0  A2WJLOXXIB7NF3     Neutral  Pocket Corduroy   
1  A1RKICUK0GG6VF    Positive  Pocket Corduroy   
2  A1QA5E50M398VW    Positive  Pocket Corduroy   
3  A3N0HBW8IP8CZQ    Positive  Pocket Corduroy   
4  A1K1JW1C5CUSUZ    Positive  Pocket Corduroy   

                                    category_for_rec  \
0  Office Products Office School Supplies Educati...   
1  Office Products Office School Supplies Educati...   
2  Office Products Office School Supplies Educati...   
3  Office Products Office School Supplies Educati...   
4  Office Products Office School Supplies Educati...   

                                 description_for_rec  \
0  Corduroy bear goes launderette Lisa overhears ...   
1  Corduroy bear goes launderette Lisa overhears ...   
2  Corduroy bear goes launderette Lisa overhears ...   
3  Corduroy bear goes launderette Lisa overhears ...   
4  Corduroy bear goes launderette Lisa overhears ...   

                                       combined_text  
0  Pocket Corduroy Office Products Office School ...  
1  Pocket Corduroy Office Products Office School ...  
2  Pocket Corduroy Office Products Office School ...  
3  Pocket Corduroy Office Products Office School ...  
4  Pocket Corduroy Office Products Office School ...

In [16]:
df2=df1[['Product_name','category_for_rec','description_for_rec','combined_text']] # taking only required column for further anlaysis

In [17]:
df2.combined_text[0]

'Pocket Corduroy Office Products Office School Supplies Education Crafts Early Childhood Education Materials Corduroy bear goes launderette Lisa overhears mother warn taking things pockets washing clothes Corduroy discovers pocket begins search find one'

In [18]:
#pip install sentence-transformers

## Sentence Embedding:
- Hugging Face's Sentence Transformers library is used to load a pre-trained model (all-MiniLM-L6-v2).
- Each combined text is encoded into a vector representation using the pre-trained model, resulting in combined_embedding.

In [19]:
from sentence_transformers import SentenceTransformer # sentence tranformer


In [20]:
model = SentenceTransformer('all-MiniLM-L6-v2') # one of model from hugging face

# Embedding

In [21]:
df2['combined_embedding']=df2['combined_text'].apply(lambda x:model.encode(x)) # encoding the text to vector

C:\Users\prabh\AppData\Local\Temp\ipykernel_8736\4155631282.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['combined_embedding']=df2['combined_text'].apply(lambda x:model.encode(x)) # encoding the text to vector


In [22]:
df2.sample(20)

Product_name  \
1868  Scholastic Teachers Friend Schedule Cards Pock...   
1340      Scholastic File Organizer Pocket Chart TF5104   
3119  Carson Dellosa 5239 KidDrawn Christian Faith S...   
3395  MarkMyTime Digital Bookmark Reading Timer Neon...   
5451  Freedom Journal Best Daily Planner Accomplish ...   
7059               CarsonDellosa File Folders CDP136002   
1550                              Standard Pocket Chart   
4377  pretty simple cards quotThank Cardsquot 12 Car...   
5113  Freedom Journal Best Daily Planner Accomplish ...   
1706  Scholastic Primary Math Charts Bulletin Board ...   
3916  Neck Traction Collar Men Women Cervical Brace ...   
9643             Knock Knock Love Mom Fill Love Journal   
1112  Rand McNally MSeries FullColor Laminated Unite...   
9398             Knock Knock Love Mom Fill Love Journal   
1958  Scholastic Classroom Resources File Organizer ...   
5286  Freedom Journal Best Daily Planner Accomplish ...   
8323                                Knock Knock Pad Red   
5919  OOLY Yummy Yummy Scented Glitter Gel Pens 1321...   
4759  Productivity Planner Daily Planner Non Dated 5...   
9124               Knock Knock High Five Nifty Note Pad   

                                       category_for_rec  \
1868  Office Products Office amp School Supplies Edu...   
1340  Office Products Office amp School Supplies Edu...   
3119  Office Products Office amp School Supplies Edu...   
3395  Office Products Office amp School Supplies Boo...   
5451  Office Products Office amp School Supplies Cal...   
7059  Office Products Office School Supplies Filing ...   
1550  Office Products Office amp School Supplies Edu...   
4377  Office Products Office School Supplies Paper C...   
5113  Office Products Office amp School Supplies Cal...   
1706                                                      
3916  Office Products Office amp School Supplies Cal...   
9643   Office Products Office amp School Supplies Paper   
1112  Office Products Office amp School Supplies Edu...   
9398   Office Products Office amp School Supplies Paper   
1958  Office Products Office amp School Supplies Edu...   
5286  Office Products Office amp School Supplies Cal...   
8323  Office Products Office amp School Supplies Pap...   
5919  Office Products Office amp School Supplies Wri...   
4759  Office Products Office amp School Supplies Cal...   
9124  Office Products Office School Supplies Paper N...   

                                    description_for_rec  \
1868         use Scholastic Daily Schedule Pocket Chart   
1340  Pocket chart features 10 sturdy pockets fit le...   
3119  Perfect reward recognition pack acidfree ligni...   
3395  bTheres product quite like accurately track ch...   
5451                                                      
7059  Make organizing fun cool bubbly blues file fol...   
1550  Pocket chart features 10 seethrough plastic po...   
4377  Simple Direct Understated Thank Notes Black Sc...   
5113                                                      
1706  allinone math reference set includes place val...   
3916  Spend Year Space awardwinning largeformat wall...   
9643  little book contains fillintheblank lines desc...   
1112  Eyecatching 50 x 32 reference piece home class...   
9398  little book contains fillintheblank lines desc...   
1958  sturdy pocket chart features 10 pockets fit le...   
5286                                                      
8323  hasnt wandered blindly grocery store trying re...   
5919  OOLY love creating products help people ages s...   
4759  Productivity Planner combines productivity pri...   
9124  Knock Knock independent maker clever gifts boo...   

                                          combined_text  \
1868  Scholastic Teachers Friend Schedule Cards Pock...   
1340  Scholastic File Organizer Pocket Chart TF5104 ...   
3119  Carson Dellosa 5239 KidDrawn Christian Faith S...   
3395  MarkMyTime Digital Bookmark Reading Timer Neon...   
5451  Freedom Journal Best D

In [23]:
df2.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Product_name         10000 non-null  object
 1   category_for_rec     10000 non-null  object
 2   description_for_rec  10000 non-null  object
 3   combined_text        10000 non-null  object
 4   combined_embedding   10000 non-null  object
dtypes: object(5)
memory usage: 390.8+ KB


In [24]:
df2.combined_embedding[0]

array([-1.13985658e-01,  2.96170972e-02,  2.20395047e-02,  1.28198704e-02,
        3.35913268e-04,  2.03762064e-03,  1.04566537e-01,  3.95324789e-02,
        3.63291777e-03,  1.43586588e-03,  5.99806979e-02,  4.42380346e-02,
       -8.74844193e-03,  3.83620858e-02, -2.00432912e-03,  5.50881736e-02,
        2.62357015e-02,  6.41684681e-02,  5.43782562e-02,  9.08802729e-03,
        5.65564372e-02,  5.05657531e-02,  6.05862029e-02, -7.71827204e-03,
       -3.28158997e-02,  1.20924011e-01, -2.05528997e-02, -1.44500554e-01,
        1.27150456e-03, -5.79404943e-02,  1.79672372e-02,  8.07602555e-02,
        6.75414205e-02,  5.05498238e-02,  4.71836179e-02,  2.55447384e-02,
        8.65877196e-02,  2.16620881e-02,  3.92201096e-02,  8.00263211e-02,
        8.73124693e-03, -3.34960967e-02, -2.30383556e-02, -4.29795682e-02,
       -1.20390449e-02, -4.59842309e-02, -1.72692221e-02,  2.66106017e-02,
        5.10983244e-02, -1.76471863e-02, -1.84013788e-02, -7.52899125e-02,
       -4.58665602e-02,  

In [25]:
#df2.to_csv('data_with_embeddings.csv',index=False)


# Cosine Similarity
- Cosine similarity is calculated between the input text and the embeddings of all products in the dataset.
- The most similar products are identified based on the cosine similarity scores.
- The top similar products are retrieved and displayed.

In [26]:
from sentence_transformers import util # cosine similarity

In [27]:
def get_similar_products(combined_input, df, top_n=2):
    combined_embedding = model.encode(combined_input)
    
    similarities = util.pytorch_cos_sim(combined_embedding, df2['combined_embedding'])
    
    print(similarities)
    
    similar_indices = similarities.argsort(descending= True,axis = 1)[0][:top_n]
    print(similar_indices)
    
    similar_items_df = df2.iloc[similar_indices][['Product_name','category_for_rec','description_for_rec']]
    #print(similar_items)
    return similar_items_df

In [28]:
product_info_to_search = "Colorful Chalkboard"

similar_items = get_similar_products(product_info_to_search,df2)
similar_items

tensor([[0.2228, 0.2228, 0.2228,  ..., 0.2378, 0.2378, 0.2378]])
tensor([7102, 7114])


C:\Users\prabh\anaconda3\lib\site-packages\sentence_transformers\util.py:39: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:264.)
  b = torch.tensor(b)


Product_name  \
7102  Colorful Chalkboard EZ Letters   
7114  Colorful Chalkboard EZ Letters   

                                       category_for_rec  \
7102  Office Products Office School Supplies Educati...   
7114  Office Products Office School Supplies Educati...   

                                    description_for_rec  
7102  DIVEasily create eyecatching messages contempo...  
7114  DIVEasily create eyecatching messages contempo...

In [29]:
print(product_info_to_search)
print("\nSimilar Products:")
for idx,row in similar_items.iterrows():
    print(f"Product : {row['Product_name']}")

Colorful Chalkboard

Similar Products:
Product : Colorful Chalkboard EZ Letters
Product : Colorful Chalkboard EZ Letters


In [30]:
product_info_to_search = input("Enter Keywords : ")

similar_items = get_similar_products(product_info_to_search,df2)
print(product_info_to_search)
print("\nSimilar Products:")
for idx,row in similar_items.iterrows():
    print(f"Product : {row['Product_name']}")
similar_items

Enter Keywords : notebook
tensor([[0.3006, 0.3006, 0.3006,  ..., 0.2912, 0.2912, 0.2912]])
tensor([3600, 3586])
notebook

Similar Products:
Product : Scientific Notebook Laboratory Notebook 192 numbered pages black hardcover 2001HC
Product : Scientific Notebook Laboratory Notebook 192 numbered pages black hardcover 2001HC


Product_name  \
3600  Scientific Notebook Laboratory Notebook 192 nu...   
3586  Scientific Notebook Laboratory Notebook 192 nu...   

                                       category_for_rec  \
3600  Office Products Office School Supplies Paper N...   
3586  Office Products Office School Supplies Paper N...   

                                    description_for_rec  
3600  Bound laboratory notebook archival quality sec...  
3586  Bound laboratory notebook archival quality sec...

**This project aims to provide users with personalized and relevant product recommendations based on textual input, thereby enhancing their shopping experience and increasing engagement with the platform.**